/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MindsRouteImport } from './routes/minds'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as FilesRouteImport } from './routes/files'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MindsSlugRouteImport } from './routes/minds_.$slug'
import { Route as IntelligenceIdRouteImport } from './routes/intelligence_.$id'
import { Route as FilesIdRouteImport } from './routes/files_.$id'

const MindsRoute = MindsRouteImport.update({
  id: '/minds',
  path: '/minds',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MindsSlugRoute = MindsSlugRouteImport.update({
  id: '/minds_/$slug',
  path: '/minds/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceIdRoute = IntelligenceIdRouteImport.update({
  id: '/intelligence_/$id',
  path: '/intelligence/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesIdRoute = FilesIdRouteImport.update({
  id: '/files_/$id',
  path: '/files/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/community': typeof CommunityRoute
  '/files': typeof FilesRoute
  '/intelligence': typeof IntelligenceRoute
  '/login': typeof LoginRoute
  '/minds': typeof MindsRoute
  '/files/$id': typeof FilesIdRoute
  '/intelligence/$id': typeof IntelligenceIdRoute
  '/minds/$slug': typeof MindsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/community': typeof CommunityRoute
  '/files': typeof FilesRoute
  '/intelligence': typeof IntelligenceRoute
  '/login': typeof LoginRoute
  '/minds': typeof MindsRoute
  '/files/$id': typeof FilesIdRoute
  '/intelligence/$id': typeof IntelligenceIdRoute
  '/minds/$slug': typeof MindsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/community': typeof CommunityRoute
  '/files': typeof FilesRoute
  '/intelligence': typeof IntelligenceRoute
  '/login': typeof LoginRoute
  '/minds': typeof MindsRoute
  '/files_/$id': typeof FilesIdRoute
  '/intelligence_/$id': typeof IntelligenceIdRoute
  '/minds_/$slug': typeof MindsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/community'
    | '/files'
    | '/intelligence'
    | '/login'
    | '/minds'
    | '/files/$id'
    | '/intelligence/$id'
    | '/minds/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/community'
    | '/files'
    | '/intelligence'
    | '/login'
    | '/minds'
    | '/files/$id'
    | '/intelligence/$id'
    | '/minds/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/community'
    | '/files'
    | '/intelligence'
    | '/login'
    | '/minds'
    | '/files_/$id'
    | '/intelligence_/$id'
    | '/minds_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CommunityRoute: typeof CommunityRoute
  FilesRoute: typeof FilesRoute
  IntelligenceRoute: typeof IntelligenceRoute
  LoginRoute: typeof LoginRoute
  MindsRoute: typeof MindsRoute
  FilesIdRoute: typeof FilesIdRoute
  IntelligenceIdRoute: typeof IntelligenceIdRoute
  MindsSlugRoute: typeof MindsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/minds': {
      id: '/minds'
      path: '/minds'
      fullPath: '/minds'
      preLoaderRoute: typeof MindsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minds_/$slug': {
      id: '/minds_/$slug'
      path: '/minds/$slug'
      fullPath: '/minds/$slug'
      preLoaderRoute: typeof MindsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence_/$id': {
      id: '/intelligence_/$id'
      path: '/intelligence/$id'
      fullPath: '/intelligence/$id'
      preLoaderRoute: typeof IntelligenceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files_/$id': {
      id: '/files_/$id'
      path: '/files/$id'
      fullPath: '/files/$id'
      preLoaderRoute: typeof FilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CommunityRoute: CommunityRoute,
  FilesRoute: FilesRoute,
  IntelligenceRoute: IntelligenceRoute,
  LoginRoute: LoginRoute,
  MindsRoute: MindsRoute,
  FilesIdRoute: FilesIdRoute,
  IntelligenceIdRoute: IntelligenceIdRoute,
  MindsSlugRoute: MindsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
